// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnvroyyxfppogrcuulvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBudnJveXl4ZnBwb2dyY3V1bHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTgxODksImV4cCI6MjA2OTQ3NDE4OX0.qJT697Cw_V93aIevQ6J8VbAwwjaw6MnLr0o0v2C-0AU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});